origins = ["BCN", "CDG", "LON", "ZRH", "AMS", 
           "FRA", "FCO", "ATH", "IST", "MAD"]


origin_info = {
    "BCN": ("Barcelona", "Spain"),
    "CDG": ("Paris", "France"),
    "LON": ("London", "United Kingdom"),
    "ZRH": ("Zurich", "Switzerland"),
    "AMS": ("Amsterdam", "Netherlands"),
    "FRA": ("Frankfurt", "Germany"),
    "FCO": ("Rome", "Italy"),
    "ATH": ("Athens", "Greece"),
    "IST": ("Istanbul", "Turkey"),
    "MAD": ("Madrid", "Spain")
}

airline_names = {
    "AJet": "AJet",
    "Aegean": "Aegean",
    "Air Algerie": "Air Algerie",
    "Air Baltic": "Air Baltic",
    "Air Dolomiti": "Air Dolomiti",
    "Air Europa": "Air Europa",
    "Air France": "Air France",
    "Air Serbia": "Air Serbia",
    "Austrian": "Austrian",
    "British Airways": "British Airways",
    "Brussels Airlines": "Brussels Airlines",
    "Condor": "Condor",
    "Croatia": "Croatia",
    "Cyprus Airways": "Cyprus Airways",
    "Discover Airlines": "Discover Airlines",
    "Edelweiss Air": "Edelweiss Air",
    "Egypt": "Egypt",
    "Eurowings": "Eurowings",
    "FLYONE": "FLYONE",
    "ITA": "ITA",
    "ITAAir Europa": "ITA",
    "ITALufthansa": "ITA",
    "ITASWISS": "ITA",
    "Iberia": "Iberia",
    "Iberia Express": "Iberia Express",
    "Jet2": "Jet2",
    "KLM": "KLM",
    "KLMAir France": "KLM",
    "KM Malta Airlines": "KM Malta Airlines",
    "LOT": "LOT",
    "Lufthansa": "Lufthansa",
    "Lufthansa City Airlines": "Lufthansa City Airlines",
    "Luxair": "Luxair",
    "Norwegian": "Norwegian",
    "Pegasus": "Pegasus",
    "Royal Air Maroc": "Royal Air Maroc",
    "Royal Jordanian": "Royal Jordanian",
    "Ryanair": "Ryanair",
    "Ryanair UK": "Ryanair UK",
    "SKY express": "SKY express",
    "SWISS": "SWISS",
    "SWISSAegean": "SWISS",
    "SWISSITA": "SWISS",
    "SWISSLufthansa": "SWISS",
    "Scandinavian Airlines": "Scandinavian Airlines",
    "Smartwings": "Smartwings",
    "Sun": "Sun",
    "TAROM": "TAROM",
    "Tap Air Portugal": "Tap Air Portugal",
    "Transavia": "Transavia",
    "Tunisair": "Tunisair",
    "Turkish Airlines": "Turkish Airlines",
    "Vueling": "Vueling",
    "Wizz Air": "Wizz Air",
    "easy": "easyJet"
}